app = "gsksksksdnbsbs82928"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = false
  auto_start_machines = true
  auto_stop_machines = false

[[http_service.ports]]
  port = 80
  handlers = ["http"]
